version: "3"
services:
    frontend:
        restart: on-failure
        build: ./frontend
        container_name: frontend
        command: npm run dev -- --host
        ports:
            - 3000:3000
            - 24678:24678
        volumes:
            - ./frontend:/app
            - /app/node_modules
